//
//  WeatherCondition.swift
//  Swift Practice 174 CWB Weather Forcast
//
//  Created by Dogpa's MBAir M1 on 2022/9/9.
//

import Foundation

struct WeatherIcon: Hashable {
    let weatherDescription:     String  //天氣描述
    let day:                    String  //對應天氣描述的白天圖示
    let night:                  String  //對應天氣描述的晚上圖示
}

struct DayAndNight {
    let day:    String      //白天圖資
    let night:  String      //晚上圖資
}

let allWeatherConditionArray = [
WeatherIcon(weatherDescription: "晴天", day: "晴天-D", night: "晴天-N"),
WeatherIcon(weatherDescription: "晴時多雲", day: "晴時多雲-D", night: "晴時多雲-N"),
WeatherIcon(weatherDescription: "多雲時晴", day: "多雲時晴-D", night: "多雲時晴-N"),
WeatherIcon(weatherDescription: "多雲", day: "多雲-D", night: "多雲-N"),
WeatherIcon(weatherDescription: "多雲時陰", day: "多雲時陰", night: "多雲時陰"),
WeatherIcon(weatherDescription: "陰時多雲", day: "陰時多雲", night: "陰時多雲"),
WeatherIcon(weatherDescription: "陰天", day: "陰天", night: "陰天"),

WeatherIcon(weatherDescription: "多雲陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "多雲短暫雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "多雲短暫陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "午後短暫陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "短暫陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "多雲時晴短暫陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "多雲時晴短暫雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "晴時多雲短暫陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "晴短暫陣雨", day: "多雲陣雨", night: "多雲陣雨"),
WeatherIcon(weatherDescription: "短暫雨", day: "多雲陣雨", night: "多雲陣雨"),

WeatherIcon(weatherDescription: "多雲時陰短暫雨", day: "多雲時陰短暫雨", night: "多雲時陰短暫雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫陣雨", day: "多雲時陰短暫雨", night: "多雲時陰短暫雨"),

WeatherIcon(weatherDescription: "陰時多雲短暫雨", day: "陰時多雲短暫雨", night: "陰時多雲短暫雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫陣雨", day: "陰時多雲短暫雨", night: "陰時多雲短暫雨"),

WeatherIcon(weatherDescription: "雨天", day: "雨天", night: "雨天"),
WeatherIcon(weatherDescription: "晴午後陰短暫雨", day: "雨天", night: "雨天"),
WeatherIcon(weatherDescription: "晴午後陰短暫陣雨", day: "雨天", night: "雨天"),
WeatherIcon(weatherDescription: "陰短暫雨", day: "雨天", night: "雨天"),
WeatherIcon(weatherDescription: "陰短暫陣雨", day: "雨天", night: "雨天"),
WeatherIcon(weatherDescription: "陰午後短暫陣雨", day: "雨天", night: "雨天"),

WeatherIcon(weatherDescription: "多雲時陰有雨", day: "多雲時陰有雨", night: "多雲時陰有雨"),
WeatherIcon(weatherDescription: "多雲時陰陣雨", day: "多雲時陰有雨", night: "多雲時陰有雨"),
WeatherIcon(weatherDescription: "晴時多雲陣雨", day: "多雲時陰有雨", night: "多雲時陰有雨"),
WeatherIcon(weatherDescription: "多雲時晴陣雨", day: "多雲時陰有雨", night: "多雲時陰有雨"),

WeatherIcon(weatherDescription: "陰時多雲有雨", day: "陰時多雲有雨", night: "陰時多雲有雨"),
WeatherIcon(weatherDescription: "陰時多雲有陣雨", day: "陰時多雲有雨", night: "陰時多雲有雨"),
WeatherIcon(weatherDescription: "陰時多雲陣雨", day: "陰時多雲有雨", night: "陰時多雲有雨"),

WeatherIcon(weatherDescription: "陰有雨", day: "陰有雨", night: "陰有雨"),
WeatherIcon(weatherDescription: "陰有陣雨", day: "陰有雨", night: "陰有雨"),
WeatherIcon(weatherDescription: "陰雨", day: "陰有雨", night: "陰有雨"),
WeatherIcon(weatherDescription: "陰陣雨", day: "陰有雨", night: "陰有雨"),
WeatherIcon(weatherDescription: "陣雨", day: "陰有雨", night: "陰有雨"),
WeatherIcon(weatherDescription: "午後陣雨", day: "陰有雨", night: "陰有雨"),
WeatherIcon(weatherDescription: "有雨", day: "陰有雨", night: "陰有雨"),



WeatherIcon(weatherDescription: "多雲陣雨或雷雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲短暫陣雨或雷雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲短暫雷陣雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲雷陣雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "短暫陣雨或雷雨後多雲", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "短暫雷陣雨後多雲", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "短暫陣雨或雷雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴時多雲短暫陣雨或雷雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴短暫陣雨或雷雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時晴短暫陣雨或雷雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
WeatherIcon(weatherDescription: "午後短暫雷陣雨", day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),


WeatherIcon(weatherDescription: "多雲時陰陣雨或雷雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫陣雨或雷雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫雷陣雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時陰雷陣雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴陣雨或雷雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴時多雲陣雨或雷雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時晴陣雨或雷雨", day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),


WeatherIcon(weatherDescription: "陰時多雲有雷陣雨", day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
WeatherIcon(weatherDescription: "陰時多雲陣雨或雷雨", day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫陣雨或雷雨", day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫雷陣雨", day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
WeatherIcon(weatherDescription: "陰時多雲雷陣雨", day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),


WeatherIcon(weatherDescription: "陰有陣雨或雷雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰有雷陣雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰陣雨或雷雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰雷陣雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴午後陰短暫陣雨或雷雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴午後陰短暫雷陣雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰短暫陣雨或雷雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰短暫雷陣雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "雷雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陣雨或雷雨後多雲", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰陣雨或雷雨後多雲", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰短暫陣雨或雷雨後多雲", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰短暫雷陣雨後多雲", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰雷陣雨後多雲", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "雷陣雨後多雲", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "陣雨或雷雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "雷陣雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
WeatherIcon(weatherDescription: "午後雷陣雨", day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),


WeatherIcon(weatherDescription: "晴午後多雲局部雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部短暫雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部短暫陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲短暫雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲短暫陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後局部雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後局部陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後局部短暫雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後局部短暫陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後短暫雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴午後短暫陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
WeatherIcon(weatherDescription: "晴時多雲午後短暫陣雨", day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),


WeatherIcon(weatherDescription: "多雲午後局部雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲午後局部陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲午後局部短暫雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲午後局部短暫陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲午後陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲午後短暫雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲午後短暫陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲時陰午後短暫陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "陰時多雲午後短暫陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
WeatherIcon(weatherDescription: "多雲時晴午後短暫陣雨", day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),


WeatherIcon(weatherDescription: "晴午後多雲陣雨或雷雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後陣雨或雷雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部陣雨或雷雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部短暫陣雨或雷雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部短暫雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲局部雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲短暫陣雨或雷雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後多雲短暫雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後局部短暫雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後局部雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴午後短暫雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴時多雲雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "晴時多雲午後短暫雷陣雨", day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),


WeatherIcon(weatherDescription: "多雲午後局部陣雨或雷雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後局部短暫陣雨或雷雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後局部短暫雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後局部雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後陣雨或雷雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後短暫陣雨或雷雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後短暫雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲午後雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲時晴雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲時晴午後短暫雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲時陰午後短暫雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "陰時多雲午後短暫雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "陰午後短暫雷陣雨", day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),




WeatherIcon(weatherDescription: "多雲局部陣雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時陰有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時陰短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),

WeatherIcon(weatherDescription: "陰時多雲有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰時多雲短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時陰有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時陰短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰時多雲有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰時多雲短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "有雨或短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰有雨或短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "陰時多雲有雨或短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時陰有雨或短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲有雨或短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時晴有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴時多雲有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴有雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時晴短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴時多雲短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴短暫雨或雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時晴有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴時多雲有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴有雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "多雲時晴短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴時多雲短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
WeatherIcon(weatherDescription: "晴短暫雪", day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),


WeatherIcon(weatherDescription: "晴有霧", day: "晴有霧-D", night: "晴有霧-N"),
WeatherIcon(weatherDescription: "晴晨霧", day: "晴有霧-D", night: "晴有霧-N"),


WeatherIcon(weatherDescription: "晴時多雲有霧", day: "晴時多雲有霧-D", night: "晴時多雲有霧-N"),
WeatherIcon(weatherDescription: "晴時多雲晨霧", day: "晴時多雲有霧-D", night: "晴時多雲有霧-N"),


WeatherIcon(weatherDescription: "多雲時晴有霧", day: "多雲時晴有霧-D", night: "多雲時晴有霧-N"),
WeatherIcon(weatherDescription: "多雲時晴晨霧", day: "多雲時晴有霧-D", night: "多雲時晴有霧-N"),


WeatherIcon(weatherDescription: "多雲有霧", day: "多雲有霧-D", night: "多雲有霧-N"),
WeatherIcon(weatherDescription: "多雲晨霧", day: "多雲有霧-D", night: "多雲有霧-N"),
WeatherIcon(weatherDescription: "有霧", day: "多雲有霧-D", night: "多雲有霧-N"),
WeatherIcon(weatherDescription: "晨霧", day: "多雲有霧-D", night: "多雲有霧-N"),


WeatherIcon(weatherDescription: "陰有霧", day: "陰有霧", night: "陰有霧"),
WeatherIcon(weatherDescription: "陰晨霧", day: "陰有霧", night: "陰有霧"),
WeatherIcon(weatherDescription: "多雲時陰有霧", day: "陰有霧", night: "陰有霧"),
WeatherIcon(weatherDescription: "多雲時陰晨霧", day: "陰有霧", night: "陰有霧"),
WeatherIcon(weatherDescription: "陰時多雲有霧", day: "陰有霧", night: "陰有霧"),
WeatherIcon(weatherDescription: "陰時多雲晨霧", day: "陰有霧", night: "陰有霧"),


WeatherIcon(weatherDescription: "多雲局部雨", day: "多雲局部雨-D", night: "多雲局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部陣雨", day: "多雲局部雨-D", night: "多雲局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫雨", day: "多雲局部雨-D", night: "多雲局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫陣雨", day: "多雲局部雨-D", night: "多雲局部雨-N"),


WeatherIcon(weatherDescription: "多雲時陰局部雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "多雲時陰局部陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "晴午後陰局部雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "晴午後陰局部陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "晴午後陰局部短暫雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "晴午後陰局部短暫陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰局部雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰局部陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰局部短暫雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰局部短暫陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫陣雨", day: "多雲時陰局部雨", night: "多雲時陰局部雨"),


WeatherIcon(weatherDescription: "多雲有霧有局部雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲有霧有局部陣雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲有霧有局部短暫雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲有霧有局部短暫陣雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲有霧有陣雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲有霧有短暫雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲有霧有短暫陣雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部雨晨霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部陣雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部陣雨晨霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫雨晨霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫陣雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫陣雨晨霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲陣雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲短暫雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲短暫雨晨霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲短暫陣雨有霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "多雲短暫陣雨晨霧", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "有霧有短暫雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
WeatherIcon(weatherDescription: "有霧有短暫陣雨", day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),


WeatherIcon(weatherDescription: "多雲時陰有霧有局部雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰有霧有局部陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰有霧有局部短暫雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰有霧有局部短暫陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰有霧有陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),

WeatherIcon(weatherDescription: "多雲時陰有霧有短暫雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰有霧有短暫陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰局部雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰局部陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),

WeatherIcon(weatherDescription: "多雲時陰局部短暫陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫雨晨霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "多雲時陰短暫陣雨晨霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰有霧有陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰局部雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰局部陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰局部短暫陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有局部雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有局部陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有局部短暫雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有局部短暫陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有短暫雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲有霧有短暫陣雨", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫雨晨霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰時多雲短暫陣雨晨霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰短暫雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰短暫雨晨霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰短暫陣雨有霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
WeatherIcon(weatherDescription: "陰短暫陣雨晨霧", day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),


WeatherIcon(weatherDescription: "多雲局部陣雨或雷雨", day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫陣雨或雷雨", day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲局部短暫雷陣雨", day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
WeatherIcon(weatherDescription: "多雲局部雷陣雨", day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),


WeatherIcon(weatherDescription: "多雲時陰局部陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "多雲時陰局部雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴午後陰局部陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴午後陰局部短暫陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴午後陰局部短暫雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "晴午後陰局部雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰局部陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰局部短暫陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰局部短暫雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰局部雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰時多雲局部陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫陣雨或雷雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
WeatherIcon(weatherDescription: "陰時多雲局部雷陣雨", day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),




WeatherIcon(weatherDescription: "多雲有陣雨或雷雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲有雷陣雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲有霧有陣雨或雷雨", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲有霧有雷陣雨", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲局部陣雨或雷雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲局部短暫陣雨或雷雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲局部短暫雷陣雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲局部雷陣雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲陣雨或雷雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲短暫陣雨或雷雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲短暫雷陣雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲雷陣雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
WeatherIcon(weatherDescription: "多雲時晴短暫陣雨或雷雨有霧", day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),


WeatherIcon(weatherDescription: "多雲時陰有陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰有雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰有霧有陣雨或雷雨", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰有霧有雷陣雨", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰局部陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰局部短暫雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰局部雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰短暫陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰短暫雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "多雲時陰雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰局部陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰局部短暫陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰局部短暫雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰局部雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲有陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲有雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲有霧有陣雨或雷雨", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲有霧有雷陣雨", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲局部陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲局部短暫雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲局部雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲短暫陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲短暫雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰時多雲雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰短暫陣雨或雷雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陰短暫雷陣雨有霧", day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),


WeatherIcon(weatherDescription: "多雲局部雨或雪有霧", day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
WeatherIcon(weatherDescription: "多雲時陰局部雨或雪有霧", day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
WeatherIcon(weatherDescription: "陰時多雲局部雨或雪有霧", day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
WeatherIcon(weatherDescription: "陰局部雨或雪有霧", day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
WeatherIcon(weatherDescription: "短暫雨或雪有霧", day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
WeatherIcon(weatherDescription: "有雨或雪有霧", day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),


WeatherIcon(weatherDescription: "短暫陣雨有霧", day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
WeatherIcon(weatherDescription: "短暫陣雨晨霧", day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
WeatherIcon(weatherDescription: "短暫雨有霧", day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
WeatherIcon(weatherDescription: "短暫雨晨霧", day: "短暫陣雨有霧", night: "短暫陣雨有霧"),


WeatherIcon(weatherDescription: "有雨有霧", day: "有雨有霧", night: "有雨有霧"),
WeatherIcon(weatherDescription: "陣雨有霧", day: "有雨有霧", night: "有雨有霧"),


WeatherIcon(weatherDescription: "短暫陣雨或雷雨有霧", day: "短暫陣雨或雷雨有霧", night: "短暫陣雨或雷雨有霧"),
WeatherIcon(weatherDescription: "陣雨或雷雨有霧", day: "短暫陣雨或雷雨有霧", night: "短暫陣雨或雷雨有霧"),


WeatherIcon(weatherDescription: "下雪", day: "下雪", night: "下雪"),
WeatherIcon(weatherDescription: "積冰", day: "下雪", night: "下雪"),
WeatherIcon(weatherDescription: "暴風雪", day: "下雪", night: "下雪"),
]


let allWeatherConditionDict = [
    "晴天" : DayAndNight(day: "晴天-D", night: "晴天-N"),
    "晴時多雲" : DayAndNight(day: "晴時多雲-D", night: "晴時多雲-N"),
    "多雲時晴" : DayAndNight(day: "多雲時晴-D", night: "多雲時晴-N"),
    "多雲" : DayAndNight(day: "多雲-D", night: "多雲-N"),
    "多雲時陰" : DayAndNight(day: "多雲時陰", night: "多雲時陰"),
    "陰時多雲" : DayAndNight(day: "陰時多雲", night: "陰時多雲"),
    "陰天" : DayAndNight(day: "陰天", night: "陰天"),
    "多雲陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "多雲短暫雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "多雲短暫陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "午後短暫陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "短暫陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "多雲時晴短暫陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "多雲時晴短暫雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "晴時多雲短暫陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "晴短暫陣雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "短暫雨" : DayAndNight(day: "多雲陣雨", night: "多雲陣雨"),
    "多雲時陰短暫雨" : DayAndNight(day: "多雲時陰短暫雨", night: "多雲時陰短暫雨"),
    "多雲時陰短暫陣雨" : DayAndNight(day: "多雲時陰短暫雨", night: "多雲時陰短暫雨"),
    "陰時多雲短暫雨" : DayAndNight(day: "陰時多雲短暫雨", night: "陰時多雲短暫雨"),
    "陰時多雲短暫陣雨" : DayAndNight(day: "陰時多雲短暫雨", night: "陰時多雲短暫雨"),
    "雨天" : DayAndNight(day: "雨天", night: "雨天"),
    "晴午後陰短暫雨" : DayAndNight(day: "雨天", night: "雨天"),
    "晴午後陰短暫陣雨" : DayAndNight(day: "雨天", night: "雨天"),
    "陰短暫雨" : DayAndNight(day: "雨天", night: "雨天"),
    "陰短暫陣雨" : DayAndNight(day: "雨天", night: "雨天"),
    "陰午後短暫陣雨" : DayAndNight(day: "雨天", night: "雨天"),
    "多雲時陰有雨" : DayAndNight(day: "多雲時陰有雨", night: "多雲時陰有雨"),
    "多雲時陰陣雨" : DayAndNight(day: "多雲時陰有雨", night: "多雲時陰有雨"),
    "晴時多雲陣雨" : DayAndNight(day: "多雲時陰有雨", night: "多雲時陰有雨"),
    "多雲時晴陣雨" : DayAndNight(day: "多雲時陰有雨", night: "多雲時陰有雨"),
    "陰時多雲有雨" : DayAndNight(day: "陰時多雲有雨", night: "陰時多雲有雨"),
    "陰時多雲有陣雨" : DayAndNight(day: "陰時多雲有雨", night: "陰時多雲有雨"),
    "陰時多雲陣雨" : DayAndNight(day: "陰時多雲有雨", night: "陰時多雲有雨"),
    "陰有雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "陰有陣雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "陰雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "陰陣雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "陣雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "午後陣雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "有雨" : DayAndNight(day: "陰有雨", night: "陰有雨"),
    "多雲陣雨或雷雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "多雲短暫陣雨或雷雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "多雲短暫雷陣雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "多雲雷陣雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "短暫陣雨或雷雨後多雲" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "短暫雷陣雨後多雲" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "短暫陣雨或雷雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "晴時多雲短暫陣雨或雷雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "晴短暫陣雨或雷雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "多雲時晴短暫陣雨或雷雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "午後短暫雷陣雨" : DayAndNight(day: "多雲陣雨或雷雨", night: "多雲陣雨或雷雨"),
    "多雲時陰陣雨或雷雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "多雲時陰短暫陣雨或雷雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "多雲時陰短暫雷陣雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "多雲時陰雷陣雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "晴陣雨或雷雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "晴時多雲陣雨或雷雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "多雲時晴陣雨或雷雨" : DayAndNight(day: "多雲時陰陣雨或雷雨", night: "多雲時陰陣雨或雷雨"),
    "陰時多雲有雷陣雨" : DayAndNight(day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
    "陰時多雲陣雨或雷雨" : DayAndNight(day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
    "陰時多雲短暫陣雨或雷雨" : DayAndNight(day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
    "陰時多雲短暫雷陣雨" : DayAndNight(day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
    "陰時多雲雷陣雨" : DayAndNight(day: "陰時多雲有雷陣雨", night: "陰時多雲有雷陣雨"),
    "陰有陣雨或雷雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰有雷陣雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰陣雨或雷雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰雷陣雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "晴午後陰短暫陣雨或雷雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "晴午後陰短暫雷陣雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰短暫陣雨或雷雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰短暫雷陣雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "雷雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陣雨或雷雨後多雲" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰陣雨或雷雨後多雲" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰短暫陣雨或雷雨後多雲" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰短暫雷陣雨後多雲" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陰雷陣雨後多雲" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "雷陣雨後多雲" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "陣雨或雷雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "雷陣雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "午後雷陣雨" : DayAndNight(day: "陰有陣雨或雷雨", night: "陰有陣雨或雷雨"),
    "晴午後多雲局部雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後多雲局部陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後多雲局部短暫雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後多雲局部短暫陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後多雲短暫雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後多雲短暫陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後局部雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後局部陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後局部短暫雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後局部短暫陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後短暫雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴午後短暫陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "晴時多雲午後短暫陣雨" : DayAndNight(day: "晴午後多雲局部雨-D", night: "晴午後多雲局部雨-N"),
    "多雲午後局部雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲午後局部陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲午後局部短暫雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲午後局部短暫陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲午後陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲午後短暫雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲午後短暫陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲時陰午後短暫陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "陰時多雲午後短暫陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "多雲時晴午後短暫陣雨" : DayAndNight(day: "多雲午後局部雨-D", night: "多雲午後局部雨-N"),
    "晴午後多雲陣雨或雷雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後陣雨或雷雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲局部陣雨或雷雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲局部短暫陣雨或雷雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲局部短暫雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲局部雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲短暫陣雨或雷雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後多雲短暫雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後局部短暫雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後局部雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴午後短暫雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴時多雲雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "晴時多雲午後短暫雷陣雨" : DayAndNight(day: "晴午後多雲陣雨或雷雨-D", night: "晴午後多雲陣雨或雷雨-N"),
    "多雲午後局部陣雨或雷雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後局部短暫陣雨或雷雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後局部短暫雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後局部雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後陣雨或雷雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後短暫陣雨或雷雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後短暫雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲午後雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲時晴雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲時晴午後短暫雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲時陰午後短暫雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "陰時多雲午後短暫雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "陰午後短暫雷陣雨" : DayAndNight(day: "多雲午後局部陣雨或雷雨-D", night: "多雲午後局部陣雨或雷雨-N"),
    "多雲局部陣雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時陰有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時陰短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰時多雲有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰時多雲短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時陰有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時陰短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰時多雲有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰時多雲短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "有雨或短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰有雨或短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "陰時多雲有雨或短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時陰有雨或短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲有雨或短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時晴有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴時多雲有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴有雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時晴短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴時多雲短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴短暫雨或雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時晴有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴時多雲有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴有雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "多雲時晴短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴時多雲短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴短暫雪" : DayAndNight(day: "多雲局部陣雨或雪", night: "多雲局部陣雨或雪"),
    "晴有霧" : DayAndNight(day: "晴有霧-D", night: "晴有霧-N"),
    "晴晨霧" : DayAndNight(day: "晴有霧-D", night: "晴有霧-N"),
    "晴時多雲有霧" : DayAndNight(day: "晴時多雲有霧-D", night: "晴時多雲有霧-N"),
    "晴時多雲晨霧" : DayAndNight(day: "晴時多雲有霧-D", night: "晴時多雲有霧-N"),
    "多雲時晴有霧" : DayAndNight(day: "多雲時晴有霧-D", night: "多雲時晴有霧-N"),
    "多雲時晴晨霧" : DayAndNight(day: "多雲時晴有霧-D", night: "多雲時晴有霧-N"),
    "多雲有霧" : DayAndNight(day: "多雲有霧-D", night: "多雲有霧-N"),
    "多雲晨霧" : DayAndNight(day: "多雲有霧-D", night: "多雲有霧-N"),
    "有霧" : DayAndNight(day: "多雲有霧-D", night: "多雲有霧-N"),
    "晨霧" : DayAndNight(day: "多雲有霧-D", night: "多雲有霧-N"),
    "陰有霧" : DayAndNight(day: "陰有霧", night: "陰有霧"),
    "陰晨霧" : DayAndNight(day: "陰有霧", night: "陰有霧"),
    "多雲時陰有霧" : DayAndNight(day: "陰有霧", night: "陰有霧"),
    "多雲時陰晨霧" : DayAndNight(day: "陰有霧", night: "陰有霧"),
    "陰時多雲有霧" : DayAndNight(day: "陰有霧", night: "陰有霧"),
    "陰時多雲晨霧" : DayAndNight(day: "陰有霧", night: "陰有霧"),
    "多雲局部雨" : DayAndNight(day: "多雲局部雨-D", night: "多雲局部雨-N"),
    "多雲局部陣雨" : DayAndNight(day: "多雲局部雨-D", night: "多雲局部雨-N"),
    "多雲局部短暫雨" : DayAndNight(day: "多雲局部雨-D", night: "多雲局部雨-N"),
    "多雲局部短暫陣雨" : DayAndNight(day: "多雲局部雨-D", night: "多雲局部雨-N"),
    "多雲時陰局部雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "多雲時陰局部陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "多雲時陰局部短暫雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "多雲時陰局部短暫陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "晴午後陰局部雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "晴午後陰局部陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "晴午後陰局部短暫雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "晴午後陰局部短暫陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰局部雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰局部陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰局部短暫雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰局部短暫陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰時多雲局部雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰時多雲局部陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰時多雲局部短暫雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "陰時多雲局部短暫陣雨" : DayAndNight(day: "多雲時陰局部雨", night: "多雲時陰局部雨"),
    "多雲有霧有局部雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲有霧有局部陣雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲有霧有局部短暫雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲有霧有局部短暫陣雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲有霧有陣雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲有霧有短暫雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲有霧有短暫陣雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部雨晨霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部陣雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部陣雨晨霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部短暫雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部短暫雨晨霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部短暫陣雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲局部短暫陣雨晨霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲陣雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲短暫雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲短暫雨晨霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲短暫陣雨有霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲短暫陣雨晨霧" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "有霧有短暫雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "有霧有短暫陣雨" : DayAndNight(day: "多雲有霧有局部雨-D", night: "多雲有霧有局部雨-N"),
    "多雲時陰有霧有局部雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰有霧有局部陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰有霧有局部短暫雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰有霧有局部短暫陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰有霧有陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰有霧有短暫雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰有霧有短暫陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰局部雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰局部陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰局部短暫雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰局部短暫陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰短暫雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰短暫雨晨霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰短暫陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲時陰短暫陣雨晨霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰有霧有陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰局部雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰局部陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰局部短暫陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有局部雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有局部陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有局部短暫雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有局部短暫陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有短暫雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲有霧有短暫陣雨" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲局部雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲局部陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲局部短暫雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲局部短暫陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲短暫雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲短暫雨晨霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲短暫陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰時多雲短暫陣雨晨霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰短暫雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰短暫雨晨霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰短暫陣雨有霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "陰短暫陣雨晨霧" : DayAndNight(day: "多雲時陰有霧有局部雨", night: "多雲時陰有霧有局部雨"),
    "多雲局部陣雨或雷雨" : DayAndNight(day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
    "多雲局部短暫陣雨或雷雨" : DayAndNight(day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
    "多雲局部短暫雷陣雨" : DayAndNight(day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
    "多雲局部雷陣雨" : DayAndNight(day: "多雲局部陣雨或雷雨-D", night: "多雲局部陣雨或雷雨-N"),
    "多雲時陰局部陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "多雲時陰局部短暫陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "多雲時陰局部短暫雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "多雲時陰局部雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "晴午後陰局部陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "晴午後陰局部短暫陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "晴午後陰局部短暫雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "晴午後陰局部雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰局部陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰局部短暫陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰局部短暫雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰局部雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰時多雲局部陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰時多雲局部短暫陣雨或雷雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰時多雲局部短暫雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "陰時多雲局部雷陣雨" : DayAndNight(day: "多雲時陰局部陣雨或雷雨", night: "多雲時陰局部陣雨或雷雨"),
    "多雲有陣雨或雷雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲有雷陣雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲有霧有陣雨或雷雨" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲有霧有雷陣雨" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲局部陣雨或雷雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲局部短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲局部短暫雷陣雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲局部雷陣雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲陣雨或雷雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲短暫雷陣雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲雷陣雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲時晴短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲有陣雨或雷雨有霧-D", night: "多雲有陣雨或雷雨有霧-N"),
    "多雲時陰有陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰有雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰有霧有陣雨或雷雨" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰有霧有雷陣雨" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰局部陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰局部短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰局部短暫雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰局部雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰短暫雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲時陰雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰局部陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰局部短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰局部短暫雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰局部雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲有陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲有雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲有霧有陣雨或雷雨" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲有霧有雷陣雨" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲局部陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲局部短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲局部短暫雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲局部雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲短暫雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰時多雲雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰短暫陣雨或雷雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "陰短暫雷陣雨有霧" : DayAndNight(day: "多雲時陰有陣雨或雷雨有霧", night: "多雲時陰有陣雨或雷雨有霧"),
    "多雲局部雨或雪有霧" : DayAndNight(day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
    "多雲時陰局部雨或雪有霧" : DayAndNight(day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
    "陰時多雲局部雨或雪有霧" : DayAndNight(day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
    "陰局部雨或雪有霧" : DayAndNight(day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
    "短暫雨或雪有霧" : DayAndNight(day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
    "有雨或雪有霧" : DayAndNight(day: "多雲局部雨或雪有霧", night: "多雲局部雨或雪有霧"),
    "短暫陣雨有霧" : DayAndNight(day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
    "短暫陣雨晨霧" : DayAndNight(day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
    "短暫雨有霧" : DayAndNight(day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
    "短暫雨晨霧" : DayAndNight(day: "短暫陣雨有霧", night: "短暫陣雨有霧"),
    "有雨有霧" : DayAndNight(day: "有雨有霧", night: "有雨有霧"),
    "陣雨有霧" : DayAndNight(day: "有雨有霧", night: "有雨有霧"),
    "短暫陣雨或雷雨有霧" : DayAndNight(day: "短暫陣雨或雷雨有霧", night: "短暫陣雨或雷雨有霧"),
    "陣雨或雷雨有霧" : DayAndNight(day: "短暫陣雨或雷雨有霧", night: "短暫陣雨或雷雨有霧"),
    "下雪" : DayAndNight(day: "下雪", night: "下雪"),
    "積冰" : DayAndNight(day: "下雪", night: "下雪"),
    "暴風雪" : DayAndNight(day: "下雪", night: "下雪")
]

func ssss () {
    let qqqq = allWeatherConditionDict["暴風雪"]?.day ?? ""
    print()
}
